[features]
seeds = false
[programs.devnet]
pool_adaptor = "8hqwuvN3Wcyoj2haZgdMzzrwLLX47ERxHZunTn87Ee3p"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/ksuphawit/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/pool-adaptor.ts"
